# Generated by Django 3.0.2 on 2020-01-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pablish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.SectionModel')),
            ],
        ),
        migrations.CreateModel(
            name='PablicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(blank=True)),
                ('image_content', models.ImageField(upload_to='media')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique_for_date='theme')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ThemeModel')),
            ],
        ),
    ]
