# Generated by Django 3.0.2 on 2020-01-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thememodel',
            old_name='create',
            new_name='day',
        ),
    ]
