# Generated by Django 3.0.2 on 2020-01-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200103_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thememodel',
            old_name='day',
            new_name='pablish',
        ),
    ]
