# Generated by Django 3.0.2 on 2020-01-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200103_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pablicationmodel',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
