# Generated by Django 3.0.4 on 2020-03-28 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_pablicationmodel_pablic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pablicationmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pablicationmodel',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='pablicationmodel',
            name='pablic',
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(blank=True)),
                ('image_content', models.ImageField(blank=True, upload_to='media')),
                ('pablish', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250)),
                ('pablic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PablicationModel')),
            ],
        ),
    ]
